# Generated by Django 3.2 on 2021-05-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('rfc', models.TextField(max_length=100, unique=True)),
                ('direccion', models.TextField(max_length=1000)),
                ('telefono', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sitio_web', models.TextField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('residente', models.CharField(max_length=255)),
                ('direccion', models.TextField(max_length=1000)),
                ('telefono', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField(max_length=1000)),
                ('telefono', models.CharField(max_length=25, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Convencional'), ('R', 'Rápido'), ('LZ', 'Lanzado'), ('AR', 'Arquitectónico'), ('RF', 'Relleno Fluido'), ('MO', 'Mortero'), ('ES', 'Estructurales'), ('AU', 'Autocompactables')], default='C', max_length=30)),
                ('resistencia', models.CharField(choices=[('100', '100'), ('200', '200'), ('250', '250'), ('300', '300'), ('350', '350'), ('400', '400'), ('650', '650')], default='200', max_length=10)),
                ('edad', models.CharField(choices=[('R01', 'R01'), ('R03', 'R03'), ('R07', 'R07'), ('R14', 'R14'), ('N', 'N')], default='N', max_length=10)),
                ('tma', models.CharField(choices=[('10', '3/8 10mm'), ('20', '3/4 20mm'), ('40', '1 1/12 40mm'), ('05', 'Arena')], default='20', max_length=20)),
                ('revenimiento', models.CharField(choices=[('06', '06 cm'), ('08', '08 cm'), ('10', '10 cm'), ('12', '12 cm'), ('14', '14 cm'), ('16', '16 cm'), ('18', '18 cm'), ('22', '20 cm')], default='14', max_length=20)),
                ('forma', models.CharField(choices=[('T', 'Tirado'), ('B', 'Bombeado')], default='14', max_length=10)),
                ('tipo_bomba', models.CharField(choices=[('Pluma', 'Bomba Pluma'), ('Estacionaria', 'Bomba Estacionaria')], default='Pluma', max_length=20)),
                ('numero_bomba', models.CharField(choices=[('BC-03 Pluma', 'BC-03 Pluma'), ('BC-04 Pluma', 'BC-04 Pluma'), ('BC-05 Pluma', 'BC-05 Pluma'), ('BC-06 Estacionaria', 'BC-06 Estacionaria')], default='BC-03 Pluma', max_length=30)),
                ('metros_adicionales', models.CharField(max_length=255)),
                ('aditivo', models.CharField(choices=[('Acelerante a 1 día', 'Acelerante a 1 día'), ('Acelerante a 14 días', 'Acelerante a 14 días'), ('Acelerante a 3 días', 'Acelerante a 3 días'), ('Acelerante a 7 días', 'Acelerante a 7 días'), ('Ahorrador de agua', 'Ahorrador de agua'), ('Autocompactable', 'Autocompactable'), ('Autocurable', 'Autocurable'), ('Fibra de acero', 'Fibra de acero'), ('Fibra de polipropileno', 'Fibra de polipropileno'), ('Fluidizante', 'Fluidizante'), ('Impermeabilizante al 1%', 'Impermeabilizante al 1%'), ('Impermeabilizante al 2%', 'Impermeabilizante al 2%'), ('Impermeabilizante al 4%', 'Impermeabilizante al 4%'), ('Inclusor de aire', 'Inclusor de aire'), ('Perlita de polipropileno', 'Perlita de polipropileno'), ('Plastificantes', 'Plastificantes'), ('Retardante', 'Retardante')], default='Acelerante a 1 día', max_length=30)),
                ('elemento_colar', models.CharField(choices=[('Arroyo', 'Arroyo'), ('Ballenas', 'Ballenas'), ('Cabezales', 'Cabezales'), ('Castillos', 'Castillos'), ('Cimentación', 'Cimentación'), ('Columnas', 'Columnas'), ('Contra trabes', 'Contra trabes'), ('Dados', 'Dados'), ('Diamantes', 'Diamantes'), ('Encofrado', 'Encofrado'), ('Escaleras', 'Escaleras'), ('Firme', 'Firme'), ('Firme pulido', 'Firme pulido'), ('Guarnición', 'Guarnición'), ('Huellas', 'Huellas'), ('Losa de azotea', 'Losa de azotea'), ('Losa de entre piso', 'Losa de entre piso'), ('Losa primer piso', 'Losa primer piso'), ('Losa segundo piso', 'Losa segundo piso'), ('Losacero', 'Losacero'), ('Muro de contención', 'Muro de contención'), ('Muros de carga', 'Muros de carga'), ('Nivelación de losa', 'Nivelación de losa'), ('Pisos', 'Pisos'), ('Rampa de acceso', 'Rampa de acceso'), ('Talud', 'Talud'), ('Zapata corrida', 'Zapata corrida'), ('Zapatas', 'Zapatas')], default='Pisos', max_length=255)),
                ('observaciones', models.CharField(max_length=255)),
                ('fecha_pedido', models.DateTimeField()),
                ('status', models.CharField(choices=[('Activado', 'Activado'), ('Desactivado', 'Desactivado')], default='Activado', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cliente', to='api.cliente')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_obra', to='api.obra')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_planta', to='api.planta')),
            ],
        ),
    ]
